spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgresdb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
path:
  url: http://name:8085/name/%d